// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseHeader: typeof import('./components/layouts/BaseHeader.vue')['default']
    BaseSide: typeof import('./components/layouts/BaseSide.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Image_upload: typeof import('./components/image_upload.vue')['default']
    Info: typeof import('./components/info.vue')['default']
    Instruction: typeof import('./components/instruction.vue')['default']
    Record: typeof import('./components/Record.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Test: typeof import('./components/test.vue')['default']
  }
}

export {}
